<img style="float: left;" src="attachment:D2Klogo.png" width="20%"> 

<center>

# Welcome to COMP 680 #
### Statistics for Computing and Data Science ###

### Homework 1 Due 9/8 by Midnight ###

### Python basics ###
- #### What can we do through Python? ####

In [ ]:
# print text
print("Hello World!")

Hello World!


In [3]:
# calculation
print (2 * 4)

8


- #### Add comments
It is good practice to add comments throughout your code. This helps you and others understand what the code is (supposed to be) doing. To add comments to the scrips, we can use the # tage.

In [ ]:
# 3 times 3 (This is the comment)
print(3 * 3)

9


* #### Calculation ####

In [5]:
# Addition and subtraction
print(1 + 1)
print(2 - 1)

2
1


In [6]:
# Multiplication and division
print(2 * 4)
print(6 / 2)

8
3.0


In [7]:
# Exponentiation
print(3 ** 2)

9


In [8]:
# Modulo
print(11 % 2)

1


* #### Variable ####
We use "=" to assign a value to a variable.

In [9]:
x = 3

We can refer to the value with its name.

In [10]:
print(x)

3


In [11]:
print(x + 2)

5


Note: "=" is the assignment symbol and cannot be used to test equality.

- Type of variables:
   - numerical:
    - int (integer): a number without a fractional part.
    - float (floating): a number that has both an integer and fractional part.
   - non-numerical:
    - str (string): a type of data to represent text.
    - bool (boolean): a type to represent logical values. (Can only be "True" or "False." Note that the first letter must be capitalized.)
    

In [12]:
# int
x = 1
# float
y = 2.3
# string
a = "Data science is great fun."
# bool
b = True

In [13]:
print(x)
print(y)
print(a)
print(b)

1
2.3
Data science is great fun.
True


* #### Variable type####
The type() function shows a variable's type.

In [14]:
type(x)

int

In [15]:
type(y)

float

In [16]:
type(a)

str

In [17]:
type(b)

bool

* #### Operations among different types of data ####

In [18]:
# Use '+' for string concatenation.
a = "Hello "
b = "World"
c = a + b
print(c)

Hello World


In [19]:
# Why error? What should we do?
a = "No doubts, "
b = "COMP "
c = 680 
d = "is great fun!"
print(a + b + c + d)

TypeError: can only concatenate str (not "int") to str

In [20]:
print(type(c))
print(type(str(c)))

<class 'int'>
<class 'str'>


In [21]:
# What did we do here to fix the error?
a = "No doubts, "
b = "COMP "
c = "680" 
d = " is great fun!"
print(a + b + c + d)

No doubts, COMP 680 is great fun!


In [22]:
# We could also use str() funtion to converse "int" to "string".
a = "No doubts, "
b = "COMP "
c = 680 
d = " is great fun!"
print(a + b + str(c) + d)

No doubts, COMP 680 is great fun!


In [23]:
# Arithmetic with boolean variables.
a = True
b = False
print(a)
print(b)
print(a + b)

True
False
1


### Python Lists ###

#### What is the list in Python?
List is a compound data type for grouping values together.

- #### Create Lists

In [24]:
# Use "[" and "]" to include the values in a list.
a = 3.14
b = 1.618
c = 2.718
d = 1.414
list_1 = [a, b, c, d]
print(type(list_1))
print(list_1)

<class 'list'>
[3.14, 1.618, 2.718, 1.414]


In [25]:
# Different data type could be contained in the same list.
a = "I love"
b = 680
list_2 = [a, b]
print(list_2)

['I love', 680]


In [26]:
# The list is one of the data type per se. This means a list
# can conctain a list.
list_3 = [list_1, list_2]
print(list_3)

[[3.14, 1.618, 2.718, 1.414], ['I love', 680]]


- #### Subsetting List

In [27]:
# You can use "[]" to perform subsetting
# Index starts from 0, which means list[1] will return the 2nd element
print(list_1[1])

1.618


In [28]:
# Why error?
print(list_3[2])

IndexError: list index out of range

In [29]:
# this will return the first element, remember what it is?
print(list_3[0])

[3.14, 1.618, 2.718, 1.414]


In [30]:
# How does the "negative" index work?
print(list_1)
print(list_1[-1])
# It counts from the last one.
print(list_1[-2])

[3.14, 1.618, 2.718, 1.414]
1.414
2.718


In [31]:
# Str() function also is applied to the list.
print(list_2[0] + " " + str(list_1))

I love [3.14, 1.618, 2.718, 1.414]


In addition to accessing list elements one at a time, Python provides concise syntax to access sublists; this is known as slicing:

In [32]:
# We could also use ":"  to slice and dice the lists.
start = 0
end = 2
print(list_1[start:end])
# Note that, the "start" index will be included,
# while the "end" index is not.

[3.14, 1.618]


In [33]:
# However, the "start" and "end" index is not necessary.
print(list_1[:2])
print(list_1[1:])
print(list_1[:])

[3.14, 1.618]
[1.618, 2.718, 1.414]
[3.14, 1.618, 2.718, 1.414]


In [34]:
print(list_3)

[[3.14, 1.618, 2.718, 1.414], ['I love', 680]]


In [35]:
# It is also possible to subset the lists of lists.
print(list_3[0][1])
# The first "[]" indicates which list are you going to subset.
# The second "[]" indicates which elements you want in this list.

1.618


In [36]:
# Create a "three level" list and perform the subset.
x = [[1, 2], [3, 4, 5], [6, 7, 8, 9]]
print(x)
print(x[1][:2])

[[1, 2], [3, 4, 5], [6, 7, 8, 9]]
[3, 4]


- #### List Manipulation

In [37]:
# Replace the list elements.
# Here we replaced the 2nd element.
print(list_2)
list_2[1] = "COMP 680"
print(list_2)

['I love', 680]
['I love', 'COMP 680']


In [38]:
print(list_1)
list_1[2:] = [-1, 1]
print(list_1)

[3.14, 1.618, 2.718, 1.414]
[3.14, 1.618, -1, 1]


In [39]:
# Extend a list
list_2 = list_2 + ["More than other classes"]
print(list_2)

['I love', 'COMP 680', 'More than other classes']


In [40]:
# Delete list elements
# "del" could do this job
# which element are we deleting here?
del list_2[2]
print(list_2)


['I love', 'COMP 680']


In [41]:
# Note that, Python is "Pass by Reference"
list_copy = list_2
print(list_copy)

# "Pass by Reference" means both the original and the copy one refer to the
# same memory location. Change either "original" or "copy" variable will
# change the value stored there.
list_copy[0] = "I really love"
print(list_2)

['I love', 'COMP 680']
['I really love', 'COMP 680']


- #### Sorting

Every Python list has a **sort method** that sorts it in place. If you don't want to mess up your list, yoiu can use the __sorted function__, which returns a new list.

In [42]:
# Example
x = [3, 1, 4, 1, 5]
y = sorted(x)
print(y)

[1, 1, 3, 4, 5]


In [43]:
# This will sort x itself
x.sort()
print(x)

[1, 1, 3, 4, 5]


By default, **sort method** (and **sorted function**) sort a list from smallest to largest. If you want elemetns sorted from largest to smallest, you can specfiy a **reverse = True** parameter. And instead of comparing the elemetns themselves, you can compare the results of a function that you specify with **key**:

In [44]:
# sort the list by absolute value from largest to smallest
x = sorted([-9, 3, 7, -4], key = abs, reverse = True)
print(x)

[-9, 7, -4, 3]


- #### Python Dictionary

Dictionaries are used to store data values in {key:value} pairs. A dictionary is a collection which is ordered, changeable and does not allow duplicates.

Dictionaries are written with curly brackets, and have keys and values:

In [45]:
fruit = {'apple':'red','orange':'orange','banana':'yellow','raspberry':'pink'}
fruit

{'apple': 'red', 'orange': 'orange', 'banana': 'yellow', 'raspberry': 'pink'}

In [46]:
xsq = {x: x**2 for x in (2, 4, 6, 8)}
xsq

{2: 4, 4: 16, 6: 36, 8: 64}

### Functions

- #### Familiar function

In [47]:
# We have already use many functions
# print(), type()
# We could use str(), int(), bool(), float() to switch between
# different data types.
a = 0
b = 1
c = -10
print(bool(a)); print(bool(b)); print(bool(c))

False
True
True


In [48]:
# help() function and "?"
#
help(type)

Help on class type in module builtins:

class type(object)
 |  type(object_or_name, bases, dict)
 |  type(object) -> the object's type
 |  type(name, bases, dict) -> a new type
 |  
 |  Methods defined here:
 |  
 |  __call__(self, /, *args, **kwargs)
 |      Call self as a function.
 |  
 |  __delattr__(self, name, /)
 |      Implement delattr(self, name).
 |  
 |  __dir__(self, /)
 |      Specialized __dir__ implementation for types.
 |  
 |  __getattribute__(self, name, /)
 |      Return getattr(self, name).
 |  
 |  __init__(self, /, *args, **kwargs)
 |      Initialize self.  See help(type(self)) for accurate signature.
 |  
 |  __instancecheck__(self, instance, /)
 |      Check if an object is an instance.
 |  
 |  __repr__(self, /)
 |      Return repr(self).
 |  
 |  __setattr__(self, name, value, /)
 |      Implement setattr(self, name, value).
 |  
 |  __sizeof__(self, /)
 |      Return memory consumption of the type object.
 |  
 |  __subclasscheck__(self, subclass, /)
 |     

In [49]:
# We could also use "?"
?type

In [50]:
# More functions
# Sorted() function

print(sorted(list_1))

[-1, 1, 1.618, 3.14]


In [51]:
# max() function: return the maximun element in a list
max(list_1)

3.14

In [52]:
# len() function: return the length (number of elements) of a list
len(list_2)

2

- #### Methods

Method and function are identical in most respects. Hoever, one of the difference between "Method" and "Function" is that Method is called for a specific object:
- Always use "Object.Method_Name" to followe the objects.

In [53]:
# String methods
# upper()
a = "i want to be a statistician."
a.upper()

'I WANT TO BE A STATISTICIAN.'

In [54]:
# lower()
a.upper().lower()

'i want to be a statistician.'

In [55]:
# count()
a.count("n")

2

In [56]:
print(list_1)

[3.14, 1.618, -1, 1]


In [57]:
# List methods
# list.index(element): return the index of a particular element
print(list_1)
list_1.index(3.14)
# Again, the first element is indexed by 0 rather than 1.

[3.14, 1.618, -1, 1]


0

In [58]:
# list.count(value): count how many elements have a particular value
list_1.count(1.618)

1

In [59]:
# list.append(element or list): append extra element or list to original list
list_2.append("Class")
print(list_2)

['I really love', 'COMP 680', 'Class']


In [60]:
# list.remove(element): remove a particular element
list_2.remove("Class")
print(list_2)

['I really love', 'COMP 680']


In [61]:
# list.reverse(): reverse the order of all elements
print(list_1)
list_1.reverse()
print(list_1)

[3.14, 1.618, -1, 1]
[1, -1, 1.618, 3.14]


### Python Libraries

- #### Also known as Package or Module #####
Python, like other programming languages, has an abundance of additional modules or libraries that augument the base framework and functionality of the language. A module is a collection of functions that can be accessed to complete certain programming tasks without having to write your own algorithm.
There are many useful packages for Python, we will use primarily on the following libraries:

* **Numpy** is a library for working with arrays of data.

* **Pandas** provides high-performance, easy-to-use data structures and data analysis tools.

* **Matplotlib** is a library for making graphs.

* **Seaborn** is a higher-level interface to Matplotlib that can be used to simplify many graphing tasks.

* **Scipy** is a library of techniques for numerical and scientific computing.

* **Statsmodels** is a library that implements many statistical techniques.



### Documentation

Reliable and accesible documentation is an absolute necessity when it comes to knowledge transfer of programming languages.  Luckily, python provides a significant amount of detailed documentation that explains the ins and outs of the language syntax, libraries, and more.  

Understanding how to read documentation is crucial for any programmer as it will serve as a fantastic resource when learning the intricacies of python.

Here is the link to the documentation of the python standard library: [Python Standard Library](https://docs.python.org/3/library/index.html#library-index)

- #### math ####
The [math](https://docs.python.org/3/library/math.html#) module provides access to some mathematical functions and special numbers such as $\pi$.

In [62]:
# Why error?
print(pi)

NameError: name 'pi' is not defined

### Importing Libraries

When using Python, you must always begin your scripts by importing the libraries that you will be using. 

In [63]:
# import math, make all functionality from "math" available.
import math
print(math.pi)

3.141592653589793


In [64]:
# from and import function to import a particular "object" from
# a specific package.

from math import pi
print(pi)


3.141592653589793


- #### NumPy ####
NumPy (short for *Numerical Python*) is a powerful package to do data science. It provides an efficient interface to store and operate dense data buffers, and it could help us perform mathmatical operation on vectors, matrices and arrays.


In [65]:
import numpy
# We could also check the current NumPy version
numpy.version.version


'1.18.5'

In [66]:
# We could also create an "alias" for our convience.
# Here, we use "np" to stand for NumPy.
import numpy as np

# The same result.
np.version.version

'1.18.5'

In [67]:
# An example one-dimensional Numpy array. 
# By default, the numbers are considered integers.
a = np.array([1,2,3,4,5])
print(a)

print(a.ndim)
print(np.ndim(a))

print(a.size)
print(np.size(a))

print(a.shape)
print(np.shape(a))


print(a.mean())
print(np.mean(a))

print(a.std())
print(np.std(a))

[1 2 3 4 5]
1
1
5
5
(5,)
(5,)
3.0
3.0
1.4142135623730951
1.4142135623730951


In [68]:
# Can instead specify that values are floats.
a = np.array([1,2,3,4,5], dtype = np.float64)
print(a)
print(a.ndim)
print(a.size)
print(a.shape)
print(a.dtype)

[1. 2. 3. 4. 5.]
1
5
(5,)
float64


In [69]:
# A two-dimensional Numpy array.
# This is a 2x5 matrix.
b = np.array([[1,2,3,4,5],[6,7,8,9,10]],dtype=np.float64)
print(b)
print(b.ndim, b.size, b.shape, b.dtype)
# ndim: the dimension of Numpy array, 1-dim is a vector, 
# 2-dim is a matrix, >2-dim is a tensor
# size: total number of elements
# shape: for 1-d array shape is the same as the size, i.e. the number of elements in the vector;
#        for 2-d array shape is (number of rows, number of columns); 

# Subsetting
print(b[1][-1])
print(b[1, -1])

[[ 1.  2.  3.  4.  5.]
 [ 6.  7.  8.  9. 10.]]
2 10 (2, 5) float64
10.0
10.0


In [70]:
# Create an array of zeros.
# A 3x3 matrix of all zeros.
np.zeros((3,3), dtype=np.float64)

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [71]:
# Create regularly-spaced numbers on an interval:
# use'linspace' if you want to specify the number of values to create 
# use 'arange' if you want to specify the step length. 
# Notice that 'linspace' includes the final endpoint while 'arange' does not!
print(np.linspace(0, 10, 5))
print(np.arange(0, 12.5, 2.5))

[ 0.   2.5  5.   7.5 10. ]
[ 0.   2.5  5.   7.5 10. ]


- #### Rnadomness

As we learn data science, will frequently need to generate random numbers, which we can do with the **random** module.

In [72]:
import random
# random.random() produces numbers uniformly between 0 and 1
# if you run this cell multiple times, you get different numbers
five_uniform_randoms = [random.random() for i in range(5)]
print(five_uniform_randoms)

[0.07452248815482632, 0.33526778826304426, 0.1547058771667985, 0.02259735206454805, 0.35127559481875625]


In [73]:
# You can set with random.seed if you want to get reproducible results.
random.seed(2021)
print(random.random())
random.seed(2021)
print(random.random())

0.8363375023320742
0.8363375023320742


In [74]:
# The random.randrange() returns an element chosen randomly from the corresponding range():
# E.g., choose randomly from range(5) = [0, 1, 2, 3, 4]
print(random.randrange(5))

4


In [75]:
# random.shuffle() randomly reorders the elements of a list.
x = [1, 2, 3, 4, 5]
print(x)
random.shuffle(x)
print(x)

[1, 2, 3, 4, 5]
[4, 1, 5, 2, 3]


In [76]:
# if you need to randomly pick one element from a list you can use random.choice:
my_best_friend = random.choice(["Alice", "Bob", "Charlie"])
print(my_best_friend)

Bob


In [77]:
# If you need to randomly choose a sample of elements without replacement
# you can use random.sample()
# this generate 10 random numbers from integers 0 to 99
without_replacement = random.sample(range(100), 10)
print(without_replacement)

[60, 73, 8, 40, 34, 37, 9, 20, 21, 6]


In [78]:
# If you need to randomly choose a sample of elements with replacement (i.e., possible duplicates),
# you can just make multiple calls to random.choice()
with_replacement = [random.choice(range(100))
                    for i in range(10)]
print(with_replacement)

[95, 13, 86, 91, 70, 37, 6, 68, 87, 59]


In [79]:
# You may consider make multiple calls to random.sample(), but what is the difference?
with_replacement = [random.sample(range(100), 1) 
                    for i in range(10)]
print(with_replacement)

[[14], [25], [77], [81], [56], [81], [35], [67], [43], [85]]


In [80]:
# Generate random numbers from the standard normal distribution
# using two approaches:  
# Note that I set the random number generator 'seed' before each call, 
# this ensures we get the same numbers.
np.random.seed(2021)
# sample from standard normal and put in shape of 2x4 matrix
print(np.random.standard_normal([2, 4]))

np.random.seed(2021)
# sample 8 numbers from normal with mean=0 and standard deviation=1
tmp = np.random.normal(0, 1, 8)
print(tmp)
# put that 8 numbers in shape of 2x4 matrix
print(np.reshape(tmp, [2, 4]))

[[ 1.48860905  0.67601087 -0.41845137 -0.80652081]
 [ 0.55587583 -0.70550429  1.13085826  0.64500184]]
[ 1.48860905  0.67601087 -0.41845137 -0.80652081  0.55587583 -0.70550429
  1.13085826  0.64500184]
[[ 1.48860905  0.67601087 -0.41845137 -0.80652081]
 [ 0.55587583 -0.70550429  1.13085826  0.64500184]]


In [81]:
# 'Stacking' arrays together. 
# 'vstack' to stack vertically.
# 'hstack' to stack horizontally. 
a = np.random.standard_normal((2,3))
b = np.random.standard_normal((2,3))

print(a, b)
print(np.vstack([a,b]))
print(np.hstack([a,b]))

[[ 0.10641374  0.42215483  0.12420684]
 [-0.83795346  0.4090157   0.10275122]] [[-1.90772239  1.1002243  -1.40232506]
 [-0.22508127 -1.33620597  0.30372151]]
[[ 0.10641374  0.42215483  0.12420684]
 [-0.83795346  0.4090157   0.10275122]
 [-1.90772239  1.1002243  -1.40232506]
 [-0.22508127 -1.33620597  0.30372151]]
[[ 0.10641374  0.42215483  0.12420684 -1.90772239  1.1002243  -1.40232506]
 [-0.83795346  0.4090157   0.10275122 -0.22508127 -1.33620597  0.30372151]]


In [82]:
# Transpose an array.
print(a)
print(a.transpose())

[[ 0.10641374  0.42215483  0.12420684]
 [-0.83795346  0.4090157   0.10275122]]
[[ 0.10641374 -0.83795346]
 [ 0.42215483  0.4090157 ]
 [ 0.12420684  0.10275122]]


In [83]:
# Save an array to file.
np.save('example.npy',a)

In [84]:
# Load an array from file.
a_in = np.load('example.npy')
print(a_in)

[[ 0.10641374  0.42215483  0.12420684]
 [-0.83795346  0.4090157   0.10275122]]


- #### Some difference compared to the regular Python list.
 - numpy array cannot contain element with different types.
 - The typical arithmatic operators (+, -, *, /) have different meaning.

In [85]:
# If try to build a list with different data type, some of the 
# elements' types are changed to end up with a homogeneous list.
# This is known as type coercion.

# NumPy array
print(np.array([True, 1]))
# Regular Python list
print([True, 1])

[1 1]
[True, 1]


In [86]:
# NumPy array
print(np.array([True, 1]) + np.array([False, 0]))

# Regular Python list
print([True, 1] + [False, 0])

[1 1]
[True, 1, False, 0]


In [87]:
# For two-dimensional NumPy array.
print(a)
print(b)
print(a + b)

[[ 0.10641374  0.42215483  0.12420684]
 [-0.83795346  0.4090157   0.10275122]]
[[-1.90772239  1.1002243  -1.40232506]
 [-0.22508127 -1.33620597  0.30372151]]
[[-1.80130865  1.52237913 -1.27811822]
 [-1.06303473 -0.92719026  0.40647273]]


In [88]:
# Why error?
a = np.array([1, 2, 3, 4, 5, 6])
print(a + b)

ValueError: operands could not be broadcast together with shapes (6,) (2,3) 

Here's your real homework starts:P. Please write your code with appropriate comments and informative names. Feel free to insert more cells as you see necessary. 

**Question 1**:
Create four Python variables with different data types.

In [89]:
# (1) 
x_1 = 6.2
x_2 = True
x_3 = 'comp680'
x_4 = ['D', 2, 'K']

print(type(x_1))
print(type(x_2))
print(type(x_3))
print(type(x_4))

<class 'float'>
<class 'bool'>
<class 'str'>
<class 'list'>


**Question 2**:
Create a Python list containing 5 numeric values.

In [131]:
my_list_num = [1, 2, 3, 4, 3.14]
print(my_list_num)

[1, 2, 3, 4, 3.14]


**Question 3**:
Perform an arithmetic operation on a subset of elements in the list you just created.

In [132]:
my_list_num[1]*my_list_num[2]-my_list_num[3]

2

**Question 4**:
Create a Python list containing 3 string values.

In [133]:
my_list_str = ['COMP', '680', '002']
print(my_list_str)

['COMP', '680', '002']


**Question 5**:
Append 2 more strings to the end of this Python list you just created.

In [134]:
my_list_str_app = my_list_str + ['Statistics', 'Inference']
# or 
# my_list_str_app = np.append(my_list_str, ['Statistics', 'Inference'])
print(my_list_str_app)

['COMP', '680', '002', 'Statistics', 'Inference']


**Question 6**:
Combine your two Python lists into a single two-dimensional list.

In [135]:
my_2d_list = [my_list_str, my_list_str_app]
print(my_2d_list)

[['COMP', '680', '002'], ['COMP', '680', '002', 'Statistics', 'Inference']]


**Question 7**:
Use any five Python functions to do some manipulations on your variables or lists. Check [here](https://docs.python.org/3/library/functions.html) for some build-in functions in [the Python Standard Library](https://docs.python.org/3/library/index.html). 

In [136]:
# any function should be fine
max(my_list_num), min(my_list_num), np.mean(my_list_num), np.median(my_list_num), np.std(my_list_num)

(4, 1, 2.628, 3.0, 1.0322480322093135)

**Question 8**:
Use any five Python methods to do some manipulations on your variables or lists. Check [here](https://docs.python.org/3/tutorial/datastructures.html) for some methods you can apply to Python lists or [Numpy array methods](https://numpy.org/doc/stable/reference/generated/numpy.ndarray.html).

In [ ]:
# any methods should be fine
my_list_num.append(999)
print(my_list_num)
print(my_list_num.count(999))
my_list_num.remove(999)
print(my_list_num)
my_list_num.insert(0, 0)
print(my_list_num)
my_list_num.clear()
print(my_list_num)

[1, 2, 3, 4, 3.14, 999]
1
[1, 2, 3, 4, 3.14]
[0, 1, 2, 3, 4, 3.14]
[]


**Question 9**:
Create a two-dimensional NumPy array.

In [138]:
my_2d_array = np.array([[1,2,3], [4,5,6]])
print(my_2d_array)

[[1 2 3]
 [4 5 6]]


**Question 10**:
Print a subset of the rows and columns of the two-dimensional Numpy array you just created.

In [139]:
my_2d_array[1,2]

6

**Question 11**: Suppose that a fair coin is tossed repeatedly until both a head and tail have appeared at least once. Describe the sample space $\Omega$ and calculate the probability that 3 tosses will be needed.

**Solution**: \
$\Omega = \{HT, TH, HHT, TTH, HHHT, TTTH, HHHHT, TTTTH, \cdots \}$ 
$\Omega = \{1, 2, 3, 4 \cdots \}$ is also fine.

3 tosses need means HHT or TTH:

$P(X = 3) = 1/2 \cdot 1/2 \cdot 1/2 \cdot 2 = 1/4$

**Question 12**: Consider rolling a die. Let $A = \{1, 2\}$, $B = \{2, 4, 6\}$, and $C = \{1, 4\}$. Show that $A$ and $B$ are independent, but not independent conditioned on $C$.

**Solution**: \
$P (A) = 1/3$, $P(B) = 1/2$, \
$P (A \cap B) = P (\{2 \}) = 1/6 = P(A) \cdot P(B)$

$P (A | C) = P (A \cap C) / P(C) = 1/2$, \
$P (B | C) = P (B \cap C) / P(C) = 1/2$, \
$P (A \cap B | C) = P (A \cap B \cap C) / P(C) =0 \neq P (A | C) \cdot P (B | C)$

**Question 13**:
For the Monty Hall problem, prove that by switching, your probablity of winning the car increases from $\frac{1}{3}$ to $\frac{2}{3}$. Hint: use Bayes Theorem!

**Solution**: \
Suppose the participant first picked door A, and Monty opened door B, the option is to switch to door C. We want to show $P(A=car | B=goat) = 1/3$ and $P(C=car | B=goat) = 2/3$:

\begin{align}
&P(A=car | B=goat) = \frac{P(B=goat | A=car ) \cdot P(A=car)}{P(B=goat)} \\
=& \frac{P(B=goat | A=car ) \cdot P(A=car)}{P(B=goat | A=car ) \cdot P(A=car) + P(B=goat | A=goat ) \cdot P(A=goat)} \\
=& \frac{1 \cdot 1/3}{1 \cdot 1/3 + 1 \cdot 2/3} = 1/3
\end{align}

\begin{align}
&P(C=car | B=goat) = \frac{P(B=goat | C=car ) \cdot P(C=car)}{P(B=goat)} \\
=& \frac{P(B=goat | C=car ) \cdot P(C=car)}{P(B=goat | C=car ) \cdot P(C=car) + P(B=goat | C=goat ) \cdot P(C=goat)} \\
=& \frac{1 \cdot 2/3}{1 \cdot 2/3 + 1 \cdot 1/3} = 2/3
\end{align}

**Question 14**:
For the Monty Hall problem, if Monty randomly choose a door to open, and it happens to be a goat. Prove that in this case, switching does not increase your probablity of wining the car! This is known as "The Random Monty Hall Problem".

**Solution**: \
Use same notation as above:
\begin{align}
&P(A=car | B=goat) = \frac{P(B=goat | A=car ) \cdot P(A=car)}{P(B=goat)} \\
=& \frac{P(B=goat | A=car ) \cdot P(A=car)}{P(B=goat | A=car ) \cdot P(A=car) + P(B=goat | A=goat ) \cdot P(A=goat)} \\
=& \frac{1 \cdot 1/3}{1 \cdot 1/3 + 1/2 \cdot 2/3} = 1/2
\end{align}

\begin{align}
&P(C=car | B=goat) = \frac{P(B=goat | C=car ) \cdot P(C=car)}{P(B=goat)} \\
=& \frac{P(B=goat | C=car ) \cdot P(C=car)}{P(B=goat | C=car ) \cdot P(C=car) + P(B=goat | C=goat ) \cdot P(C=goat)} \\
=& \frac{1/2 \cdot 2/3}{1/2 \cdot 2/3 + 1\cdot 1/3} = 1/2
\end{align}

**Question 15**:
Let $X$ have probability density function:
$$ f_X(x) = \begin{cases} \frac{1}{4} \quad &0 < x < 1 \\
\frac{3}{8} \quad &3 < x < 5 \\
0 \quad &\text{otherwise} \\
\end{cases}
$$
Find the cdf of $X$.

**Solution**: \
$$ F_X(x) = \begin{cases} 0 \quad & x \leq 0 \\
\int_0^x \frac{1}{4} dx  = \frac{1}{4}x \quad &0 < x \leq 1 \\
\int_0^1 \frac{1}{4} dx = \frac{1}{4} \quad &1 < x \leq 3 \\
 \int_0^1 \frac{1}{4} dx + \int_3^x \frac{3}{8} dx = \frac{1}{4} + \frac{3}{8}(x - 3) \quad &3 < x \leq 5 \\
\int_0^1 \frac{1}{4} dx + \int_3^5 \frac{3}{8} dx = 1 \quad & x > 5 \\
\end{cases}
$$

**Question 16**:
Let $X$ have probability density function in previous question. Let $Y = 1/X$. Find the probability density function $f_Y(y)$ for $Y$.

(Hint: consider 3 cases: $\frac{1}{5} \leq y \leq \frac{1}{3}$, $\frac{1}{3} \leq y \leq 1$ and $y \geq 1$.)

**Solution**: \
$$
F_Y(y) = P(Y \leq y) = P(1/X \leq y) = P(X \geq 1/y) = 1 - F_X(1/y) \\
= \begin{cases} 1 - \frac{1}{4y}  \quad & y \geq 1 \\
\frac{3}{4} \quad &\frac{1}{3} \leq y < 1 \\
\frac{3}{4} + \frac{3}{8}(3 - \frac{1}{y}) \quad &\frac{1}{5} \leq y < \frac{1}{3} \\
0 \quad & y < \frac{1}{5} \\
\end{cases}
$$

$$ f_Y(y) = F'_Y(y) \begin{cases}
\frac{3}{8y^2} \quad &\frac{1}{5} \leq y < \frac{1}{3} \\
\frac{1}{4y^2} \quad & y \geq 1\\
0 \quad &\text{otherwise}\\
\end{cases}
$$


**Question 17**:
Let $X$ be a continous random variable with pdf $f_X(x)$ and cdf $F_X(x)$. Let $A$ be a subset of the real line. Let $I_A(x)$ be the indicator function for A:
$$ I_A(x) = \begin{cases} 1 \quad x \in A \\
0 \quad x \not\in A 
\end{cases}$$
Let $Y = I_A(x)$. Find an expression for the cdf of Y. 

(Hint: first find the probablity mass function for $Y$.)

**Solution**: \
Y can only take values 0 and 1, therefore is a discrete random variable. \
The PMF for Y:\
$ P(Y = 1) = P(x \in A) = \int_A f_X(x) dx$, \
$P(Y = 0) = 1 - P(x \in A) = 1 - \int_A f_X(x) dx$\
The CDF for Y:
$$ F_Y(y) = \begin{cases} 0 \quad & y < 0 \\
1 - \int_A f_X(x) dx \quad & 0 \leq y < 1 \\
1 \quad & y \geq 1 
\end{cases}$$

**Question 18**: Let $X$ and $Y$ have the joind pdf:
$$ f_{X, Y}(x, y) = \begin{cases} c( x + y^2) \quad &0 \leq x \leq 1 \text{ and } 0 \leq y \leq 1 \\
0 \quad &\text{otherwise} \end{cases} $$
Find the value of c.

**Solution**: 
$$ \int_0^1 \int_0^1 f_{X, Y}(x, y) dx dy = \frac{5}{6} c = 1 \Rightarrow c = \frac{6}{5}$$

**Question 19**: Let  𝑋  and  𝑌  have the same joind pdf as previous problem. Find the marginal pdf of Y.

**Solution**: \
To get the marginal pdf of Y, need to integrate X over its domain: $\int_0^1 f_{X, Y}(x, y) dy = \frac{6}{5}\left( \frac{1}{2} + y^2 \right)$

$$ f_Y(y) = \begin{cases} \frac{6}{5}\left( \frac{1}{2} + y^2 \right) &0 \leq y \leq 1 \\
0 \quad &\text{otherwise} \end{cases} $$

**Question 20**: Let  𝑋  and  𝑌  have the same joind pdf as previous problem. Find $P(X < \frac{1}{2} | Y = \frac{1}{2})$

**Solution**: \
We need to first find the conditional pdf of $X$ conditioned on $Y=\frac{1}{2}$:
$$
f_X(x | Y = \frac{1}{2}) = \frac{f_{X, Y}(x, y)}{f_Y(y)} |_{y=\frac{1}{2}}= \frac{\frac{6}{5} ( x + \frac{1}{2}^2)}{\frac{6}{5}(\frac{1}{2} + \frac{1}{2}^2)} = \frac{4x+1}{3}
$$

$$ P(X < \frac{1}{2} | Y = \frac{1}{2}) = \int_0 ^{\frac{1}{2}}\frac{4x+1}{3} dx = \frac{1}{3} $$

You're done with HW 1!  Be sure to...

* **Save and Checkpoint** from the File menu,
* **Close and Halt** from the File menu,
* **Rename your ipynb file**, replacing LASTNAME with your last name,
* **Upload** your file to the course website.